format = """\
[╭╴](fg:red)\
$username\
$directory\
(\
    $git_branch\
    $git_status\
)\
(\
    $python\
    $conda\
    $nodejs\
)\
$fill$cmd_duration$time$all\
[╰─](fg:red)$character\
"""
# Add the modules you need

# Disables the blank line at the start of the prompt
add_newline = true

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[fill]
symbol = " "

[username]
style_user = 'text'
style_root = 'text'
format = '[]($style)[ wissar](bg:$style fg:base)[]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[󰍟](fg:red)"
error_symbol = "[󰍟](fg:maroon)"

[directory]
format = " [](fg:mauve)[  $path ]($style)[$read_only]($read_only_style)[](fg:mauve)"
truncation_length = 2
style = "fg:base bg:mauve"
read_only_style = "fg:base bg:mauve"
before_repo_root_style = "fg:base bg:mauve"
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[time]
disabled = false
format = " [](fg:blue)[ $time]($style)[](fg:blue)"
time_format = "%H:%M"
style = "fg:base bg:blue"

[cmd_duration]
format = " [](fg:pink)[ $duration]($style)[](fg:pink)"
style = "fg:base bg:pink"
min_time = 500

[git_branch]
format = " [](fg:yellow)[$symbol$branch](fg:base bg:yellow)[](fg:yellow)"
symbol = " "

[git_status]
format = '([ ](fg:teal)[ $all_status$ahead_behind ]($style)[](fg:teal))'
style = "fg:base bg:teal"

[docker_context]
disabled=true
symbol = " "

[package]
disabled=true

[java]
format = "[ ](fg:maroon)[$symbol$version](bg:maroon fg:base)[](fg:maroon)"
version_format = "${raw}"
symbol = " "
disabled = true

[nodejs]
format = "[ ](fg:green)[$symbol$version]($style)[](fg:green)"
style = "bg:green fg:base"
symbol = " "
version_format = "${raw}"
disabled=false

[rust]
format = "[ ](fg:rust)[$symbol$version](bg:rust fg:base)[](fg:rust)"
symbol = " "
version_format = "${raw}"
disabled=true

[python]
disabled=false
format = '[ ](fg:sapphire)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](fg:sapphire)'
symbol = " "
version_format = "${raw}"
style = "fg:base bg:sapphire"

[conda]
format = "[ ](fg:lavender)[$symbol$environment]($style)[](fg:lavender)"
style = "bg:lavender fg:base"
ignore_base = false
disabled=false
symbol = " "

[c]
format = "[ ](fg:sky)[$symbol($version(-$name) )](bg:sky fg:base)[](fg:sky)"
symbol = " "
version_format = "${raw}"
disabled=true

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
